services:
  - type: web
    name: it-occupation-api
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MYSQLHOST
        value: viaduct.proxy.rlwy.net
      - key: MYSQLPORT
        value: 3306
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: SmNGJTkiYEiwOesYWUlsgQSLBrSLutpP
      - key: MYSQLDATABASE
        value: railway 